export const immigrationofficerMockPatients = [
    {
        firstName: "Bing Bong",
        lastName: "Big",
        email: "boiboibib@gamil.com",
        address: "BIGBONG",
        phoneNumber: "41414141414",
        postalCode: "h1h1h1",
        city: "bongbong",
        hasCovid: false,
        id: "3",
        gender: "bing bong",
        dob: "2000-08-28",
        age: 21,
        height: 89,
    },
    {
        firstName: "Bob",
        lastName: "Johnson",
        email: "bob.johnson@gmail.com",
        address: "123 sesame street",
        phoneNumber: "123 456 7890",
        postalCode: "1k1 k1k",
        city: "Whatevercity",
        hasCovid: true,
        id: "2",
        gender: "attack helicopter",
        dob: "2012-12-12",
        age: 12,
        height: 12,
    },
];
