name: CI v2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allow manual action
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16 #idk our node version
          cache: "npm"
          cache-dependency-path: |
            frontend/package-lock.json
            backend/package-lock.json
      - name: Install Node  (Should usually be cached unless refreshed)
        run: |
          cd frontend
          npm ci
          cd ../backend
          npm ci

      - name: Create env file
        run: |
          touch ./backend/.env
          echo ADMIN_EMAIL_SENDER_PASSWORD=${{ secrets.ADMIN_EMAIL_SENDER_PASSWORD }} > ./backend/.env
          cat ./backend/.env

      - name: frontend tests
        run: |
          cd frontend
          npm test

      # Runs a set of commands using the runners shell
      - name: backend tests
        run: |
          cd backend
          npm test
