name: CI v1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow manual action
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14 #idk our node version

      - name: frontend tests
        run: |
          cd frontend
          npm test
          

      # Runs a set of commands using the runners shell
      - name: backend tests
        run: |
          cd backend
          npm test
